23 sprint
ShACKAL762/play-list-maker pull request #18
Opened 2024-08-22 23:08 UTC by ShACKAL762

2024-08-24 04:09 UTC, DmitrijEgorow commented
- [ ] Кнопка не соответствует дизайн-макету
![Screenshot_20240824_100842](https://github.com/user-attachments/assets/63b60eeb-58ef-4348-adaf-40d594d65e38)
![Screenshot_20240824_100900](https://github.com/user-attachments/assets/4c66d3e3-b348-4d7d-a3ff-8dd45328256d)

2024-08-24 04:10 UTC, DmitrijEgorow commented
- [ ] Разметка должна быть адаптивной, не нужно хардкодить размеры
<img width="300" alt="Screenshot 2024-08-24 at 10 10 20" src="https://github.com/user-attachments/assets/dfe41ecd-46f2-4f21-b1cc-019a47e37a2a">
<img width="266" alt="Screenshot 2024-08-24 at 10 10 52" src="https://github.com/user-attachments/assets/be896321-fea9-43e6-b5d7-bf4b95ffc4d6">

2024-08-24 04:12 UTC, DmitrijEgorow commented
- [ ] Длительность композиции (вместе с разделяющей точкой) всегда должна оставаться видимой
<img width="300" alt="Screenshot 2024-08-24 at 10 11 07" src="https://github.com/user-attachments/assets/42aacba4-2a2d-48b5-b6c2-9d4650995a5b">

2024-08-24 04:13 UTC, DmitrijEgorow commented
- [ ] Кроме заголовка ничего нет

https://github.com/user-attachments/assets/f121e558-0738-4e54-8bd2-73f19ccd9b63

2024-08-24 04:14 UTC, DmitrijEgorow commented
- [ ] Не очень хороший UX, когда список каждый раз обновляется (и отправляется новый поисковой запрос) просто при переходе обратно по стеку с аудиоплеера
- [ ] Приложение аварийно завершается

https://github.com/user-attachments/assets/e3fc799c-35d3-4b42-96c5-d2185b042dc7

```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 9917  
java.lang.IllegalStateException: Fragment CreateAlbumFragment{b6e4553} (f62b6801-fc23-4b0a-8e21-fd62ba69e7ff id=0x7f090097 tag=b265b60c-6826-4ee0-96bc-48f518acb6c3) does not have any arguments.  
at androidx.fragment.app.Fragment.requireArguments(Fragment.java:804)  
at com.example.playlistmaker.ui.library.activity.CreateAlbumFragment.checkInput(CreateAlbumFragment.kt:103)  
at com.example.playlistmaker.ui.library.activity.CreateAlbumFragment.onViewCreated(CreateAlbumFragment.kt:96)  
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)  
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:600)  
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)  
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2152)  
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2053)  
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)  
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:702)  
at android.os.Handler.handleCallback(Handler.java:938)  
at android.os.Handler.dispatchMessage(Handler.java:99)  
at android.os.Looper.loop(Looper.java:223)  
at android.app.ActivityThread.main(ActivityThread.java:7656)  
at java.lang.reflect.Method.invoke(Native Method)  
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)  
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

2024-08-24 04:15 UTC, DmitrijEgorow commented
- [ ] Синий текст плохо читается, стоит переделать на белый в тёмной теме
![Screenshot_20240824_103034](https://github.com/user-attachments/assets/0d9d5cdd-0297-4ac8-9df7-e525551b7d67)

2024-08-24 04:16 UTC, DmitrijEgorow commented
- [ ] Отсутствуют скругления у обложек
![Screenshot_20240824_103241](https://github.com/user-attachments/assets/75eb52d1-0bc7-4bda-a553-60fc4cee6941)

2024-08-24 04:17 UTC, DmitrijEgorow commented
- [ ] Стоит сделать обрезку под квадратное соотношение сторон, сохранив скругления
![Screenshot_20240824_103305](https://github.com/user-attachments/assets/98b20f15-967e-4db5-8df4-92e7b0ea077a)

2024-08-24 04:18 UTC, DmitrijEgorow commented
- [ ] Не соответствует дизайн-макету
![Screenshot_20240824_105129](https://github.com/user-attachments/assets/139af220-889c-4665-8938-4e587e4a9f44)

2024-08-24 04:18 UTC, DmitrijEgorow commented
❌Если пользователь находится на экране «Плейлист» и видит список треков, то при нажатии на элемент списка пользователь перенаправляется на экран «Аудиоплеер» ❌с данными, соответствующими выбранному элементу.

https://github.com/user-attachments/assets/4488047d-fd05-470f-89ab-88b001430521

2024-08-24 04:23 UTC, DmitrijEgorow commented
- [ ] Приложение аварийно завершается при смене конфигурации (например, изменение темы / unfold / открытие в режиме плавающего / разделённого окна)


https://github.com/user-attachments/assets/ae01a5b0-29fd-43d3-b525-e1b55949d1b2

```
FATAL EXCEPTION: main  
Process: com.example.playlistmaker, PID: 4618  
kotlin.UninitializedPropertyAccessException: lateinit property binding has not been initialized  
at com.example.playlistmaker.ui.search.activity.SearchFragment.onSaveInstanceState(SearchFragment.kt:152)  
at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3314)  
at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:714)  
at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:217)  
at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2652)  
at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:727)  
at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:217)  
at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2652)  
at androidx.fragment.app.FragmentManager.lambda$attachController[5](tex://5)androidx-fragment-app-FragmentManager(FragmentManager.java:2929)  
at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda5.saveState(Unknown Source:2)  
at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)  
at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)  
at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:374)  
at android.app.Activity.performSaveInstanceState(Activity.java:2260)  
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1563)  
at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:6503)  
at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5849)  
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6457)  
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6341)  
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)  
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)  
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)  
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)  
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)  
at android.os.Handler.dispatchMessage(Handler.java:106)
```

2024-08-24 04:34 UTC, DmitrijEgorow requested changes

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/domain/entity/Album.kt
> +    var time: Long
Лучше оставить в [data class только неизменяемые свойства](https://www.reddit.com/r/Kotlin/comments/qibnqc/comment/hijhupt/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/library/activity/AlbumsListFragment.kt
> +        Log.e("On", "Resume")
Такие логи лучше убрать

На эту тему можно [посмотреть доклад разработчика из Яндекса](https://youtu.be/ydwuccVwYBM?si=pwgTEsqUG-G7Kcxm&t=513)

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/library/activity/CreateAlbumFragment.kt
> +        if(requireArguments().size()>0) {
Перед коммитом стоит приводить файлы к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/playlist/activity/PlayListFragment.kt
> +    lateinit var album: Album
```suggestion
    private lateinit var binding: PlaylistFragmentBinding
    private lateinit var album: Album
```

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/playlist/activity/PlayListFragment.kt
> +
Много пустых строчек

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/ui/playlist/viewModel/PlayListViewModel.kt
> +        viewModelScope.launch(Dispatchers.IO) {
[https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers](https://developer.android.com/kotlin/coroutines/coroutines-best-practices#inject-dispatchers)

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/res/layout/playlist_fragment.xml
> +            android:id="@+id/arrow_back"
Разные стили именования идентификаторов, выше было с camelCase

2024-08-24 04:34 UTC, DmitrijEgorow commented on app/src/main/res/layout/playlist_fragment.xml
> +            android:layout_width="24dp"
Лучше вынести в dimens

2024-08-24 04:34 UTC, DmitrijEgorow commented
[Что это за название пакета? Лучше убрать](https://github.com/ShACKAL762/play-list-maker/blob/a931a08636f8a6cfabf1217bbf03aab03a59e153/app/src/main/java/com/example/playlistmaker/fueches/TrackFormat.kt#L1)

2024-08-24 04:36 UTC, DmitrijEgorow commented
[Для наименования пакетов обычно не используют заглавные буквы](https://github.com/ShACKAL762/play-list-maker/blob/a931a08636f8a6cfabf1217bbf03aab03a59e153/app/src/main/java/com/example/playlistmaker/domain/search/InteractorImpl/HistoryTrackListInteractorImpl.kt#L1)

Подробнее про стиль можно прочитать в [документации](https://kotlinlang.org/docs/coding-conventions.html#naming-rules) или [здесь](https://developer.android.com/kotlin/style-guide#package_names)

2024-08-25 16:26 UTC, DmitrijEgorow commented
> * [ ]  Разметка должна быть адаптивной, не нужно хардкодить размеры
> 
> <img alt="Screenshot 2024-08-24 at 10 10 20" width="300" src="https://private-user-images.githubusercontent.com/36837067/361100978-dfe41ecd-46f2-4f21-b1cc-019a47e37a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDM0NDMsIm5iZiI6MTcyNDYwMzE0MywicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMDA5NzgtZGZlNDFlY2QtNDZmMi00ZjIxLWIxY2MtMDE5YTQ3ZTM3YTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE2MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OTNlMjkxMjM3ZGM1YWQ1NDUyZGY4MzEyZWI1OGE5M2YxMTMwZjkwMjhlNGRlZjEyYzRhNzU5MWNlZmM4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UblPJlNDwBB_grPta7BI7TDxCWczHxktVBZL1QVhd0E"> <img alt="Screenshot 2024-08-24 at 10 10 52" width="300" src="https://private-user-images.githubusercontent.com/36837067/361100989-be896321-fea9-43e6-b5d7-bf4b95ffc4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDM0NDMsIm5iZiI6MTcyNDYwMzE0MywicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMDA5ODktYmU4OTYzMjEtZmVhOS00M2U2LWI1ZDctYmY0Yjk1ZmZjNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE2MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YThhYTEzMTZmNDQyMDIxY2JlMzc4NDk3ZTgyZTE1Zjc5MTA4ZmNmY2E0MGIwMTY3ZDU3ZTAzMWE3ZDZiMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FieSaW3LnA-MrmhMZbbuzZxMGjXtlcaIg2qylfsUx94"> <img alt="Screenshot 2024-08-24 at 10 11 34" width="300" src="https://private-user-images.githubusercontent.com/36837067/361101087-8fbde56c-2386-4250-8444-c504e7d2d43d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDM0NDMsIm5iZiI6MTcyNDYwMzE0MywicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMDEwODctOGZiZGU1NmMtMjM4Ni00MjUwLTg0NDQtYzUwNGU3ZDJkNDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE2MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDgyZTcyY2UyMTgyNjMxNWNiMWYyNWI1N2EzNWNiNDBmMmZiNWM5ZGJhMThkZGY5NWRjN2ZiZjQwZjY2ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZQJAHlcefxU0-jqsqhudL5wC5gkPfPVhC02LsEyUbM">

Актуально

2024-08-25 16:26 UTC, DmitrijEgorow commented
> * [ ]  Длительность композиции (вместе с разделяющей точкой) всегда должна оставаться видимой
> 
> <img alt="Screenshot 2024-08-24 at 10 11 07" width="300" src="https://private-user-images.githubusercontent.com/36837067/361101064-42aacba4-2a2d-48b5-b6c2-9d4650995a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDM0NDMsIm5iZiI6MTcyNDYwMzE0MywicGF0aCI6Ii8zNjgzNzA2Ny8zNjExMDEwNjQtNDJhYWNiYTQtMmEyZC00OGI1LWI2YzItOWQ0NjUwOTk1YTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE2MjU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNzVmYTNkNzMyODE3NjJmZWRkZTQ4YzA0MTg1Mzc4ZTQ1NTE3ZDYwM2Q4ZjM1ZTU2YjQ1NzgxOGVmNzU0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mFqCWdo-QMECY_ECAfMY7OsKOjz37PFkyWTpJeyk4f8">

Особенно, этот момент

2024-08-25 16:27 UTC, DmitrijEgorow commented
- [ ] Длительность композиции (вместе с разделяющей точкой) всегда должна оставаться видимой. Обрезка исполнителя должна происходить не в случайном месте экрана, а только когда текст начинает прижиматься к правому краю
<img width="300" alt="Screenshot 2024-08-25 at 23 18 11" src="https://github.com/user-attachments/assets/d01d9b02-1bd6-49ac-98db-cd39c4b260a0">

2024-08-25 16:29 UTC, DmitrijEgorow commented
- [ ] Никак не вызвать меню и никак не поделиться плейлистом, например, на Pixel 2. Пользователь, не зная заранее, даже не догадается, что его обделили функционалом

https://github.com/user-attachments/assets/8056ee4a-92f8-483c-a2a8-80a1a66a7f5e

2024-08-25 16:30 UTC, DmitrijEgorow commented
- [ ] В качестве данных для отправки должен использоваться текст: название и описание плейлиста, количество треков, пронумерованный список треков плейлиста в формате: ✅[номер].✅ [имя исполнителя] - ❌[название трека] ❌([продолжительность трека]).


https://github.com/user-attachments/assets/053375d7-d9d7-4a2d-b3ae-b5b3cba76abf

2024-08-25 16:32 UTC, DmitrijEgorow commented
- [ ] 00 минут -> 0 минут

![Screenshot_20240825_233134](https://github.com/user-attachments/assets/d9b7d6a5-3479-481f-ac8a-d67e2b787038)

2024-09-01 18:28 UTC, ShACKAL762 commented
Многие ко многим переделаю потом для себя, спасибо за статью

2024-10-14 03:42 UTC, merged